### ISSUE TITLE
Configure CI and start deploying to CompSoc server

### ISSUE THREAD

**Issue by rphi** [compsoc-edinburgh/website2017#38]
Low priority for now, but it would be nice at some stage to get something like [Travis CI](https://travis-ci.org/) building the site and automatically pushing (from a protected branch on this repository) to its destination server.

**Comment by bnelo12** [comment]
Have you heard of Githooks. I've used those for deployment before. It's basically a shell script that runs when you push to a remote Git repository that you host on your server. Super easy to implement.

**Comment by rphi** [comment]
I'm pretty sure I've used them (or was it webhooks?) to trigger a CI before... the only reason I was thinking of a CI integrated with GitHub as opposed to a far simpler script running on the server is that it will add nice check marks to the pull requests and things - also as we're open source it would be free so why not?

**Comment by qaisjp** [comment]
The check marks are desirable. (i.e lets use Travis)

**Comment by rphi** [comment]
Just seen this is now live on comp-soc.com - I have looked into travis but I can't set that up for this repository because of some kind of permissions issue. What's the current deploy pipeline? Also, just had a thought, it might be worth adding a tooltip to the GitHub icon in the footer so you can quickly see which commit the live site is running, I would hope you could dynamically insert that during build.

**Comment by qaisjp** [comment]
It's a cold launch to see if everything is working properly, and so that I can link to certain pages in certain emails. This issue will have to wait since the CompSoc server will be reset once we get physical access (i.e, when Tardis moves from the Informatics Forum to Appleton Tower)

**Comment by hreeder** [comment]
>the only reason I was thinking of a CI integrated with GitHub as opposed to a far simpler script running on the server is that it will add nice check marks to the pull requests and things - also as we're open source it would be free so why not?

You can set build status by the API [pretty easily](https://github.com/google/go-github/blob/master/github/repos_statuses.go)

Whatever happens there will need to be scripting server-side to receive some level of hooks before the site gets (re)deployed.

In past we were considering having some kind of all singing all dancing system where each PR was spun up maybe in its own container or something, hosted on a subdomain (ie 123.pulls.comp-soc.com or something) and then master could also hook into said system for auto deployment.

On what @qaisjp mentions however, I _do_ want to entirely rebuild Jupiter (the comp-soc server) when we have physical access again, and input at this stage would definitely go a long way to getting things set up in the first place rather than trying to retrofit around what I install.

**Comment by qaisjp** [comment]
I like the dancing system. I'm a fan of complicated things. +1

**Comment by neanias** [comment]
@tbrb, but in Elixir, right (mostly /s)


On 08 Aug, 2017, at 05:25 PM, Qais Patankar <notifications@github.com> wrote:


I like the dancing system. I'm a fan of complicated things. +1

**Comment by rphi** [comment]
I'm guessing this can be closed as I think we are using GitHub Pages @qaisjp ?

**Comment by qaisjp** [comment]
Yeah, you are correct.

We may need to revive this issue later though.
